# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 871)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Backgrounds/images/E-LogoHub_Wallpaper_1024x1024.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame\n"
"{\n"
"border-image: url(:/Backgrounds/images/WallpaperFusion-circum-polaire-3840x1080-M2.jpg);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 40, 631, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 40pt \"Uroob\";")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(12, 152, 1096, 535))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.stackedPages = QtWidgets.QStackedWidget(self.widget)
        self.stackedPages.setStyleSheet("#stackedPages\n"
"{\n"
"\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"}")
        self.stackedPages.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedPages.setObjectName("stackedPages")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.groupBox_2)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.userPass = QtWidgets.QLineEdit(self.groupBox_2)
        self.userPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.userPass.setObjectName("userPass")
        self.gridLayout.addWidget(self.userPass, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.submitBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.submitBtn.setAutoDefault(False)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout.addWidget(self.submitBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 127, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.stackedPages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.faceName = QtWidgets.QLineEdit(self.page_2)
        self.faceName.setText("")
        self.faceName.setObjectName("faceName")
        self.verticalLayout_5.addWidget(self.faceName)
        self.addFaceBtn = QtWidgets.QPushButton(self.page_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Backgrounds/images/kisspng-computer-icons-user-profile-icon-design-add-to-cart-button-5ad698003f7dd7.4764400015240130562601.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFaceBtn.setIcon(icon1)
        self.addFaceBtn.setObjectName("addFaceBtn")
        self.verticalLayout_5.addWidget(self.addFaceBtn)
        self.statusDisplay = QtWidgets.QLabel(self.page_2)
        self.statusDisplay.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.statusDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.statusDisplay.setText("")
        self.statusDisplay.setObjectName("statusDisplay")
        self.verticalLayout_5.addWidget(self.statusDisplay)
        self.detectFaceBtn = QtWidgets.QPushButton(self.page_2)
        self.detectFaceBtn.setObjectName("detectFaceBtn")
        self.verticalLayout_5.addWidget(self.detectFaceBtn)
        self.cameraWindow = QtWidgets.QLabel(self.page_2)
        self.cameraWindow.setMinimumSize(QtCore.QSize(420, 280))
        self.cameraWindow.setMaximumSize(QtCore.QSize(420, 280))
        self.cameraWindow.setText("")
        self.cameraWindow.setObjectName("cameraWindow")
        self.verticalLayout_5.addWidget(self.cameraWindow)
        self.verticalLayout_5.setStretch(5, 1)
        self.stackedPages.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.stackedPages)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/Backgrounds/images/FR_Front_Page.jpg"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFoo_py = QtWidgets.QAction(MainWindow)
        self.actionFoo_py.setObjectName("actionFoo_py")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.stackedPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition"))
        self.label.setText(_translate("MainWindow", "Facial Recognition and Authentication"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.userName.setPlaceholderText(_translate("MainWindow", "Adam"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.userPass.setPlaceholderText(_translate("MainWindow", "mydogrocks"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))
        self.submitBtn.setShortcut(_translate("MainWindow", "Return"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.addFaceBtn.setText(_translate("MainWindow", "Add Face"))
        self.detectFaceBtn.setText(_translate("MainWindow", "Detect Face"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionFoo_py.setText(_translate("MainWindow", "Foo.py"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
import app_resources_rc
